version: "3"
nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
  depends_on:
    - manager-server
    - manager-client
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  networks:
    - keepers-network
networks:
  keepers-network:
