filebeat.inputs:
  - type: filestream
    paths:
      - /app/logs/server.log
    parsers:
      - ndjson:
        overwrite_keys: true
        add_error_key: true
        expand_keys: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: "${ELASTIC_HOST}"
  api_key: ${ELASTIC_API_KEY}
  output.elasticsearch.index: "keeper-manager1.0-%{[agent.version]}"
  setup.template.name: "keeper-manager1.0-%{[agent.version]}"
  setup.template.pattern: "keeper-manager1.0-%{[agent.version]}"
